### PR TITLE
Disable boss actions by default in non-vanilla episodes

### LINKED ISSUE #482: SIGIL E5M8 Boss Death flags active
I was recently playing `SIGIL_v1_21.wad` in PrBoom+ 2.6.2 on HNTR, but when I reached the final level, the game unexpectedly cut to the end when I defeated the Spiderdemon boss. I think it was designed for any source port's non-vanilla (>4) episodes to have boss flags inactive by default for their respective final levels, but I believe those flags have been enabled on accident. Using `SIGIL_COMPAT_v1_21.wad` does not have this issue as it has specific DEHACKED flags to disable the Spiderdemon's boss death flags on E3M8.

I have not tested this on HMP or UV, where a Cyberdemon will also spawn, to see how it affects the boss flags.

I have observed this bug in multiple source ports, the main ones being Woof!, Crispy Doom, and PrBoom+. I wasn't sure if it was a shared piece of code between these source ports causing the issue or if they each have unique issues, but I am intending to make unique bug reports for each one.

### PR DESCRIPTION
**Pull request by FozzeY**
Fixes #482.

### CODE REVIEW

**Comment by kraflab** [comment]
This is a demo-compatibility-violating change as well as a change to the umapinfo specification. We cannot make such changes lightly.

**Comment by kraflab** [comment]
There are multiple fixes already in the linked issue, so I don't think this needs a code change.

**Comment by JadingTsunami** [comment]
Hmm, I'm not convinced this is an advisable change.

In the case this code addresses, the WAD author has supplied a UMAPINFO but did not supply bossaction(s). It would be a surprise in that case to override game-default behaviors as the UMAPINFO specification is explicit that the default is to defer to the original source code implementation.

I agree with @kraflab; this solution would be a UMAPINFO specification update, plus demo-breaking, and would need to be coordinated across all the ports at the same time. I also don't see the benefit here: if an author supplies a UMAPINFO, why not supply the explicit boss actions (or `clear` them) as intended?

The linked issue is a complaint about the source code behavior, not UMAPINFO, as I see it.

**Comment by FozzeY** [comment]
Fair enough.

**Pull request closed without merging**
