### PR TITLE
add manifest to declare app as DPI aware, so that Windows will not apply DPI virtualization

### LINKED ISSUE #192: [Issue] The Video Rendering within the Window Scales to Windows-Set System-Wide Scale.
ApplicationFrameHost_B1CzYRCP2b
I cannot have my Windows set at 150% scale (as shown in photo) as it will scale and misalign the actual video rendered inside PrBoom+. it works fine when the scale is 100% but was wondering if there is any way that this can be fixed to not scale or scale properly with system-wide scaling?

### LINKED ISSUE #266: Screen appears cut off in OpenGL mode
Running PrBoom+ on my father's laptop, When I set video mode to OpenGL, the screen appears cut off.
The laptop's screen scale set to 125%, and the resolution is 1920x1080.
Please make the game screen appears correctly on higher than 100%  scale.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #192, fixes #266

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
This requires more testing, I only have sparse access to a Windows system.

**Comment by fabiangreffrath** [comment]
Also, screenshots in both windowed and fullscreen modes for both software and hardware renderer (worked for me, but this is only one system).

**Comment by fabiangreffrath** [comment]
While it "works for me" :tm:, I'd appreciate if anyone else could test this branch as well to see if the issue is resolved and if screenshots still work as expected. Thanks!

**Comment by UnluckySpade7** [comment]
I did some messing around and unfortunately this does not fix the issue, still zooms in on the bottom left and print-screening causes a black image.

**Comment by fabiangreffrath** [comment]
Hm, are you sure that the manifest has been built and linked into the binary? Which compiler did you use?

**Comment by UnluckySpade7** [comment]
I used the auto-compiler provided by github and the vs_64 build.

**Comment by fabiangreffrath** [comment]
Ah, thanks! Could you try the gcc build, please?

**Comment by UnluckySpade7** [comment]
I don't have access to a linux system sadly.

**Comment by fabiangreffrath** [comment]
This is a Windows-only change. Anyway, I forgot we do not provide a MinGW/gcc build through CI, so sorry for that. I'll try to find a solution that serves both MSVC and MinGW/gcc tomorrow.

**Comment by fabiangreffrath** [comment]
Could you please try again with today's build?

**Comment by UnluckySpade7** [comment]
Tested at both 125% and 150% scaling and it worked.

**Comment by fabiangreffrath** [comment]
Yeeha!

**Pull request merged**
