### PR TITLE
Add support for non-latin paths and filenames on Windows

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by rfomin** [comment]
I don't know why the Visual Studio build is failing, it works on my system. Problem with manifest?

**Review by alexey-lysiuk — COMMENTED** [review]
You need to add new files to [game server target](https://github.com/coelckers/prboom-plus/blob/87fef9d2aa3d4eea1625f86ce9d33cac5cdce832/prboom2/src/CMakeLists.txt#L423) as well.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by alexey-lysiuk** [comment]
I don't like unrelated changes added to pull requests. In this case, it's a modification of `.gitignore`. Although, if others are OK with that, go ahead and merge it.

**Comment by fabiangreffrath** [comment]
Thank you @rfomin !

**Comment by rfomin** [comment]
> modification of `.gitignore`

Oops, that was a mistake, sorry.

**Comment by fabiangreffrath** [comment]
> Oops, that was a mistake, sorry.

Darn, I merged it seconds before your reply. Well, at least that line doesn't do any harm. But feel free to remove it again if you prefer.

**Pull request merged**
