### PR TITLE
Show a message when demo recording starts.

### PR DESCRIPTION
**Pull request by JadingTsunami**
Address #515 by printing a message to the user's view when recording begins.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
As already stated earlier, I like the idea to provide confirmation to the player that a demo is recording. @rfomin What do you say for Woof?

**Review by fabiangreffrath — APPROVED** [review]

**Comment by rfomin** [comment]
> As already stated earlier, I like the idea to provide confirmation to the player that a demo is recording. @rfomin What do you say for Woof?

But we have a PR for parameter validation in Woof.

**Comment by fabiangreffrath** [comment]
> But we have a PR for parameter validation in Woof.

Just as an additional confirmation for the user that the current run is recorded. I see this independent from command line validation.

**Comment by rfomin** [comment]
> Just as an additional confirmation for the user that the current run is recorded. I see this independent from command line validation.

Okay, sure.

**Comment by fabiangreffrath** [comment]
@JadingTsunami Could you consider this solution? 

https://github.com/fabiangreffrath/woof/commit/bf2710559c43af7d32ff28516cee2c702d5751fd

**Comment by JadingTsunami** [comment]
> @JadingTsunami Could you consider this solution?
> 
> [fabiangreffrath/woof@bf27105](https://github.com/fabiangreffrath/woof/commit/bf2710559c43af7d32ff28516cee2c702d5751fd)

Sure, I am fine with that as well. The downside of hard-coding the message is that it is not possible to localize it through a patch anymore. But I am not sure anyone would have a strong feeling about it; it may not matter in the end.

**Comment by JadingTsunami** [comment]
Some updates after adopting the proposed approach from @fabiangreffrath.

- `record` will print the demo filename being recorded to.
- `-recordfromto` now shows when recording continues (which is a welcome addition, I think).

**Pull request merged**
