### PR TITLE
add support for Hexen-format maps (without ACS)

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by coelckers** [comment]
Since this doesn't convert the specials to anything usable I do not see much of a point to add this right now. It's a good start for a working implementation, though.

**Comment by fabiangreffrath** [comment]
Well, at least it loads these maps now and doesn't crash anymore. It doesn't allow for much more than map exploration as it currently is, though, that's granted.

**Comment by fabiangreffrath** [comment]
> Since this doesn't convert the specials to anything usable

Do you know of a Hexen-linedef-to-generalized-linedef converter available?

**Comment by coelckers** [comment]
No, such a thing does not exist. The Hexen types are far more versatile than Boom's generalized types and to a large degree not compatible,

**Comment by fabiangreffrath** [comment]
Hm, okay, but maybe we could translate the most basic types so that it is at least possible to e.g. open a door or use a teleporter?

**Comment by kraflab** [comment]
@fabiangreffrath I think we can close this one. What do you think?

**Comment by fabiangreffrath** [comment]
Oh, yes, I think this can be closed by now. 😅

**Pull request closed without merging**
