### PR TITLE
fix scaled time interpolation

### PR DESCRIPTION
**Pull request by fabiangreffrath**
@rfomin @kraflab Am I doing this right?

### CODE REVIEW

**Comment by rfomin** [comment]
I'm sorry, I'm busy right now. I'll take a look at this later today.

**Comment by rfomin** [comment]
It works in my testing, but there is a jump of several frames when changing the speed. Perhaps these lines are relevant:
https://github.com/coelckers/prboom-plus/blob/98c3615b0639acc441b6aa8f8425de0eeec79f3f/prboom2/src/d_client.c#L352-L354

**Comment by fabiangreffrath** [comment]
> It works in my testing, but there is a jump of several frames when changing the speed. Perhaps these lines are relevant:

Hm, maybe this code was necessary with the old implementation but now plays against the new one?

**Comment by fabiangreffrath** [comment]
Oh, wait, apparently `I_GetTime_Scaled()` is missing a calculation for `ms_to_next_tick`. Maybe that's related.

**Comment by rfomin** [comment]
> Hm, maybe this code was necessary with the old implementation but now plays against the new one?

I tried to remove it - no effect. DSDA-Doom has these lines.

**Comment by fabiangreffrath** [comment]
Could you please check if this new approach has fixed it for you?

**Comment by rfomin** [comment]
Just tested DSDA-Doom, it has a small jump too. So I think it's fine.

**Comment by fabiangreffrath** [comment]
I still consider `ms_to_next_tick` to be the culprit. Could you please check again?

**Comment by rfomin** [comment]
> I still consider `ms_to_next_tick` to be the culprit. Could you please check again?

Still the same jump. I don’t know, maybe this is how it should work.

**Pull request merged**
