### PR TITLE
fix custom episode select for Doom 2

### PR DESCRIPTION
**Pull request by rfomin**
By default, Doom 2 has 4 episodes in the current UMAPINFO implementation. There are few UMAPINFO files out in the wild that don't aware of that.
Before:
doom00
After:
doom00

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Aren't you supposed to explicitly call `episode = clear` in that case?

**Comment by rfomin** [comment]
It's not clear in the specification, also doesn't make sense - Doom 2 doesn't have 4 episodes.

**Comment by fabiangreffrath** [comment]
Makes sense. Could you please clarify the spec and increase the revision log?

**Review by fabiangreffrath — APPROVED** [review]
LGTM

**Comment by fabiangreffrath** [comment]
Any objections anyone?

**Comment by JadingTsunami** [comment]
Personally I would instead initialize `EpiDef` correctly based on gamemode/gamemission instead of waiting for a customization to apply the correct values. But this is perhaps just stylistic preference.

Also if we are fixing Doom 2 we should fix Chex Quest also; this would mean checking for `(gamemode == commercial || gamemission == chex)` like is done in `m_menu.c:710`.

**Comment by fabiangreffrath** [comment]
I think @JadingTsunami is right. @rfomin Could you please add chex to the check (and the docs)?

**Comment by rfomin** [comment]
> add chex to the check (and the docs)

Does this mean that every port that implements UMAPINFO must support Chex Quest to some extent?

**Comment by fabiangreffrath** [comment]
> > add chex to the check (and the docs)
> 
> Does this mean that every port that implements UMAPINFO must support Chex Quest to some extent?

I don't think so, but most do anyway. 😉

**Pull request merged**
