### PR TITLE
add a "-pistolstart" command line parameter

### LINKED ISSUE #132: Way to automatically "pistol start" every level (feature)
**Expected:**
Convenient way to "pistol start" every level.
In this "mode" the player starts each and every level with:
* 50 bullets and no other ammo
* a pistol, a fist and no other weapon
* 100% health and 0% armor

Player starts each and every level as if they just died and just respawned - automatically.

**Actual:**
Player has to remember to type IDCLEV... or to press Home when each new level starts after finishing the previous level.

**Possible solution:**
`-pistolstart` command line switch [like in crispy-doom](https://github.com/fabiangreffrath/crispy-doom/pull/659)

**Extra:**
It's not a huge deal I suppose as the IDCLEV... way is the way many/most of us always done "pistol start" all along I'd imagine but it would be nice if this could be automated/forced. I sometimes forget to press Home on a new level and then realise it later that I should restart the level as it wasn't a pistol start. In crispy-doom the command line switch works really conveniently.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #132.

### CODE REVIEW

**Comment by D3Archi** [comment]
How about making an additional menu option to force pistol start by default as well?

**Comment by fabiangreffrath** [comment]
I want to avoid adding a menu switch that breaks with regular gameplay in such a drastic way and is incompatible with anything else that this port focuses on.

**Comment by kraflab** [comment]
Since we've been adding cheats, what do you think about making this a cheat instead of a command-line option? 🤔 
Then it doesn't work while recording anyway, and people can toggle it while in-game (and for the non-command-line-inclined). Just an idea 🤷

**Comment by D3Archi** [comment]
I don't really think cheat suits well here. Cheats are situational, tntcl would be useful for those who launch different cl2/9/11 wads without command line parameters, and shorttics are only useful in some cases as well.

Forcing player start was already implemented in prboom+ good enough, pressing "home" button starts the level from player start. But since a new command line parameter is being introduced I think it would be fair to add an option in menu to enable player starts by default. For example, default complevel and shorttics are already in cfg.

**Comment by kraflab** [comment]
I guess there are people who mostly play with pistol start only, so maybe it makes sense to be in the menu. That said, I'm not sure I would do anything personally - as archi mentioned, the restart map key already does well enough when people want to pistol start.

**Comment by fabiangreffrath** [comment]
I have just merged this, so it is at least *possible* to have pistol starts. The decision whether there will be a menu switch for this or not is orthogonal to this.

**Pull request merged**
