### PR TITLE
preserve complevel after using cheat for the rest of the session

### PR DESCRIPTION
**Pull request by D3Archi**
Right now it gets replaced with default value from config each time you reset level or change level

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
LGTM

**Comment by fabiangreffrath** [comment]
So, this preserves complevels changes in-game across level starts. How about the complevel set on the command line, which one gets precedence?

**Comment by D3Archi** [comment]
For single player: cheat > command-line parameter > cfg value.
For demo playback cheat is not accessible, old rules apply.

**Comment by fabiangreffrath** [comment]
Sounds reasonable. @kraflab ?

**Comment by kraflab** [comment]
> For single player: cheat > command-line parameter > cfg value.

It looks to me like command-line parameter wins. Am I missing something?
```c
  compatibility_level = last_compatibility_level;
  {
    int i = M_CheckParm("-complevel");
    if (i && (1+i) < myargc) {
      int l = G_GetNamedComplevel(myargv[i+1]);;
      if (l >= -1) compatibility_level = l;
    }
  }
```

**Comment by D3Archi** [comment]
That is right, I completely missed that.

Separating default config from current session config would help a lot with all those extra CheckParam calls I believe.

**Comment by fabiangreffrath** [comment]
So, how do we proceed with this?

**Comment by D3Archi** [comment]
I want to make a dedicated structure for settings that are only changeable during session, like complevel, shorttics and most other stuff that is applied via command line parameters, so that it doesn't interfere with default settings and game wouldn't have to decide which setting to load, the one from command like or one from default values. Not a big fan of code calling M_CheckParm in runtime.

**Comment by fabiangreffrath** [comment]
This is a bit dirty. But since the complevel set by cheating can only get overridden by the one set on the command line, you could check after cheating if the command line contains the `-complevel` string and modify the `argv[]` array so that the next element points to a char array that overrides the actual command line choice.

**Comment by fabiangreffrath** [comment]
Probably like this:
```patch
static void force_set_complevel (void)
{
  int i;
  static char str[4] = "";

  while ((i = M_CheckParm("-complevel")) == 0)
    M_AddParam("-complevel");

  snprintf(str, sizeof(str), "%d", complevel);

  if ((i+1) < myargc)
    myargv[i+1] = str;
  else
    M_AddParam(str);
}
```

**Comment by kraflab** [comment]
As we're gearing up for a final release and the port is only in maintenance mode as it is, going to close this one.

**Pull request closed without merging**
