### PR TITLE
allow MBF sky transfers in all complevels

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
1. This makes the `-allow_sky_transfer_in_boom` obsolete (actually, it already is), so it should be removed.
2. This needs a compatibility flag (similar to e.g. "Sky is unaffected by invulnerability") for purists.

**Comment by fabiangreffrath** [comment]
What's the general opinion on this one?

**Review by kraflab — APPROVED** [review]
Makes sense to me

**Comment by fabiangreffrath** [comment]
One last question: Should this be enabled by default, as in e.g. Crispy, or disabled as in previous versions of PrBoom+?

**Comment by fabiangreffrath** [comment]
Another last question: Native speakers, is it "in all complevels", "on all complevels" or "for all complevels"?

**Comment by kraflab** [comment]
In this context, all three of those are correct, but the one I would use is "in". 🤠

**Comment by fabiangreffrath** [comment]
> One last question: Should this be enabled by default, as in e.g. Crispy, or disabled as in previous versions of PrBoom+?

I guess I'll go with "disabled by default" to make this change less disruptive.

**Comment by kraflab** [comment]
> > One last question: Should this be enabled by default, as in e.g. Crispy, or disabled as in previous versions of PrBoom+?
> 
> I guess I'll go with "disabled by default" to make this change less disruptive.

Makes sense to me as well

**Pull request merged**
