### PR TITLE
attempt to fix stuttering with uncapped framerate

### LINKED ISSUE #400: Stuttering with Uncapped Framerate enabled (SOLVED in DSDA-Doom commit 17f1b84)
As described in the title, with uncapped framerate enabled, stuttering occurs.
With a 60hz monitor, uncapped framerate enabled and vsync active, you will notice some pretty pronounced stuttering.
With higher refresh rates, the problem is reduced but doesn't go away (at 144hz it is slight but still present).
Owning a 144hz freesync monitor, I was able to test if, with uncapped framerate disabled (35 fps), stuttering was still present and it wasn't, so I guess there is something wrong with uncapped framerate code (probably remained unsolved for years).
Woof! has no problems and It is very smooth, maybe it is possible to bring the part of the code concerning the uncapped framerate from Woof! to Prboom-plus?
I want to specify that I have always had this type of problem with Prboom-plus, with all the versions I have tried (2.5.1.5, 2.5.1.5um, 2.5.1.6um, etc.), with different PCs and monitors, and it happens both on Windows (main PC) and Linux (on an old laptop).

EDIT
Ticket #379 could be about the same problem, I have opened a new issue to try to better explain what happens.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Based on the code from DSDA-Doom and instructions by @kraflab.
Hopefully fixes #400.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Maybe @tpoppins could post a test build with this patch applied so @Kappa971 and @srludicolo could confirm the fix?

**Comment by Kappa971** [comment]
Of course. Is this the branch to compile? https://github.com/coelckers/prboom-plus/tree/unstutter

**Comment by fabiangreffrath** [comment]
Yes, that's it.

**Comment by Kappa971** [comment]
Unfortunately, stuttering is still present.

**Comment by tpoppins** [comment]
> 
> 
> Maybe @tpoppins could post a test build with this patch applied so @Kappa971 and @srludicolo could confirm the fix?

[prboom-plus-unstutter-test-w32.zip](prboom-plus-unstutter-test-w32.zip)

**Comment by Kappa971** [comment]
> [prboom-plus-unstutter-test-w32.zip](prboom-plus-unstutter-test-w32.zip)

The link doesn't work. I can share my package 
[prboom-plus-unstutter_win64.zip](https://github.com/coelckers/prboom-plus/files/7527567/prboom-plus-unstutter_win64.zip)

Anyway I have already tested it and unfortunately it doesn't solve the problem.

**Comment by srludicolo** [comment]
I can test it when I get home, but if @Kappa971 still experiences the problem, it's unlikely it'll fix the issue on my system.

**Comment by srludicolo** [comment]
I second what he said, the problem is still present.

**Comment by kraflab** [comment]
The next thing to try would probably be to drop the whole tic_vars.start / next / step code and just evaluate the time within a tic directly when calculating the frac value.

**Comment by fabiangreffrath** [comment]
Next try, please.

**Comment by Kappa971** [comment]
> Next try, please.

I'll definitely try it tomorrow.

**Comment by srludicolo** [comment]
I can try it now, but I have no idea how to compile the source code, sadly. I know a lot about the Doom engine, but have a very rudimentary idea of how programming works :(

**Comment by tpoppins** [comment]
commit da8b19e:
[prboom-plus-unstutter-test2-w32.zip](https://www.mediafire.com/file/dp4d8303128mu75/prboom-plus-unstutter-test2-w32.zip/file)

**Comment by srludicolo** [comment]
Great Scott, it works! Great job guys!

**Comment by Kappa971** [comment]
I think the stuttering has gone, in case I detect something in the future, I will report it :)
Maybe you could also release PrBoom-plus 2.6.2?

**Comment by fabiangreffrath** [comment]
Thanks for confirmation!

**Pull request merged**
